name: Reddit Chainlink EA
description: Post to Reddit
node_identifier: reddit-cl-ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Reddit
    url: https://www.reddit.com/
parameters:
  - sr
  - kind
  - resubmit
  - title
  - text
  - endpoint
  - url
